// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

public struct ComputeThreatListDiffResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The type of response. This may indicate that an action must be taken by the
  /// client when the response is received.
  public var responseType: ComputeThreatListDiffResponse.ResponseType =
    ComputeThreatListDiffResponse.ResponseType()

  /// A set of entries to add to a local threat type's list.
  public var additions: ThreatEntryAdditions? = nil

  /// A set of entries to remove from a local threat type's list.
  /// This field may be empty.
  public var removals: ThreatEntryRemovals? = nil

  /// The new opaque client version token. This should be retained by the client
  /// and passed into the next call of ComputeThreatListDiff as 'version_token'.
  /// A separate version token should be stored and used for each threatList.
  public var newVersionToken: Foundation.Data = Foundation.Data()

  /// The expected SHA256 hash of the client state; that is, of the sorted list
  /// of all hashes present in the database after applying the provided diff.
  /// If the client state doesn't match the expected state, the client must
  /// discard this diff and retry later.
  public var checksum: ComputeThreatListDiffResponse.Checksum? = nil

  /// The soonest the client should wait before issuing any diff
  /// request. Querying sooner is unlikely to produce a meaningful diff.
  /// Waiting longer is acceptable considering the use case.
  /// If this field is not set clients may update as soon as they want.
  public var recommendedNextDiff: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `ComputeThreatListDiffResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeThreatListDiffResponse().with { $0.responseType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The expected state of a client's local database.
  public struct Checksum: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The SHA256 hash of the client state; that is, of the sorted list of all
    /// hashes present in the database.
    public var sha256: Foundation.Data = Foundation.Data()

    /// Initialize a new instance of `Checksum`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Checksum().with { $0.sha256 = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.webrisk.v1.ComputeThreatListDiffResponse.Checksum"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of response sent to the client.
  public enum ResponseType: Codable, Equatable, Sendable {
    /// Unknown.
    case unspecified
    /// Partial updates are applied to the client's existing local database.
    case diff
    /// Full updates resets the client's entire local database. This means
    /// that either the client had no state, was seriously out-of-date,
    /// or the client is believed to be corrupt.
    case reset
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .diff: return 1
      case .reset: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESPONSE_TYPE_UNSPECIFIED"
      case .diff: return "DIFF"
      case .reset: return "RESET"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResponseType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESPONSE_TYPE_UNSPECIFIED": self = .unspecified
      case "DIFF": self = .diff
      case "RESET": self = .reset
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResponseType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .diff
      case 2: self = .reset
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .diff: return try container.encode(1)
      case .reset: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.webrisk.v1.ComputeThreatListDiffResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
