// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes an API diff request.
public struct ComputeThreatListDiffRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The threat list to update. Only a single ThreatType should be
  /// specified per request. If you want to handle multiple ThreatTypes, you must
  /// make one request per ThreatType.
  public var threatType: ThreatType = ThreatType()

  /// The current version token of the client for the requested list (the
  /// client version that was received from the last successful diff).
  /// If the client does not have a version token (this is the first time calling
  /// ComputeThreatListDiff), this may be left empty and a full database
  /// snapshot will be returned.
  public var versionToken: Foundation.Data = Foundation.Data()

  /// Required. The constraints associated with this request.
  public var constraints: ComputeThreatListDiffRequest.Constraints? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComputeThreatListDiffRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeThreatListDiffRequest().with { $0.threatType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let threatType = CodingKeys(stringValue: "threatType")
    static let versionToken = CodingKeys(stringValue: "versionToken")
    static let constraints = CodingKeys(stringValue: "constraints")

    static let _knownKeys: Set<Swift.String> = [
      "threatType",
      "versionToken",
      "constraints",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(ThreatType.self, forKey: .threatType) {
      self.threatType = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .versionToken) {
      self.versionToken = value
    }
    self.constraints = try container.decodeIfPresent(
      ComputeThreatListDiffRequest.Constraints.self, forKey: .constraints)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.threatType, forKey: .threatType)
    try container.encode(self.versionToken, forKey: .versionToken)
    try container.encodeIfPresent(self.constraints, forKey: .constraints)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The constraints for this diff.
  public struct Constraints: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The maximum size in number of entries. The diff will not contain more
    /// entries than this value.  This should be a power of 2 between 2**10 and
    /// 2**20.  If zero, no diff size limit is set.
    public var maxDiffEntries: Swift.Int32 = Swift.Int32()

    /// Sets the maximum number of entries that the client is willing to have
    /// in the local database. This should be a power of 2 between 2**10 and
    /// 2**20. If zero, no database size limit is set.
    public var maxDatabaseEntries: Swift.Int32 = Swift.Int32()

    /// The compression types supported by the client.
    public var supportedCompressions: [CompressionType] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Constraints`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Constraints().with { $0.maxDiffEntries = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let maxDiffEntries = CodingKeys(stringValue: "maxDiffEntries")
      static let maxDatabaseEntries = CodingKeys(stringValue: "maxDatabaseEntries")
      static let supportedCompressions = CodingKeys(stringValue: "supportedCompressions")

      static let _knownKeys: Set<Swift.String> = [
        "maxDiffEntries",
        "maxDatabaseEntries",
        "supportedCompressions",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxDiffEntries) {
        self.maxDiffEntries = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxDatabaseEntries) {
        self.maxDatabaseEntries = value
      }
      if let value = try container.decodeIfPresent(
        [CompressionType].self, forKey: .supportedCompressions)
      {
        self.supportedCompressions = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.maxDiffEntries, forKey: .maxDiffEntries)
      try container.encode(self.maxDatabaseEntries, forKey: .maxDatabaseEntries)
      try container.encode(self.supportedCompressions, forKey: .supportedCompressions)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.webrisk.v1.ComputeThreatListDiffRequest.Constraints"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.webrisk.v1.ComputeThreatListDiffRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
