// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

public struct ComputeThreatListDiffResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The type of response. This may indicate that an action must be taken by the
  /// client when the response is received.
  public var responseType: ComputeThreatListDiffResponse.ResponseType =
    ComputeThreatListDiffResponse.ResponseType()

  /// A set of entries to add to a local threat type's list.
  public var additions: ThreatEntryAdditions? = nil

  /// A set of entries to remove from a local threat type's list.
  /// This field may be empty.
  public var removals: ThreatEntryRemovals? = nil

  /// The new opaque client version token. This should be retained by the client
  /// and passed into the next call of ComputeThreatListDiff as 'version_token'.
  /// A separate version token should be stored and used for each threatList.
  public var newVersionToken: Foundation.Data = Foundation.Data()

  /// The expected SHA256 hash of the client state; that is, of the sorted list
  /// of all hashes present in the database after applying the provided diff.
  /// If the client state doesn't match the expected state, the client must
  /// discard this diff and retry later.
  public var checksum: ComputeThreatListDiffResponse.Checksum? = nil

  /// The soonest the client should wait before issuing any diff
  /// request. Querying sooner is unlikely to produce a meaningful diff.
  /// Waiting longer is acceptable considering the use case.
  /// If this field is not set clients may update as soon as they want.
  public var recommendedNextDiff: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComputeThreatListDiffResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeThreatListDiffResponse().with { $0.responseType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let responseType = CodingKeys(stringValue: "responseType")
    static let additions = CodingKeys(stringValue: "additions")
    static let removals = CodingKeys(stringValue: "removals")
    static let newVersionToken = CodingKeys(stringValue: "newVersionToken")
    static let checksum = CodingKeys(stringValue: "checksum")
    static let recommendedNextDiff = CodingKeys(stringValue: "recommendedNextDiff")

    static let _knownKeys: Set<Swift.String> = [
      "responseType",
      "additions",
      "removals",
      "newVersionToken",
      "checksum",
      "recommendedNextDiff",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      ComputeThreatListDiffResponse.ResponseType.self, forKey: .responseType)
    {
      self.responseType = value
    }
    self.additions = try container.decodeIfPresent(ThreatEntryAdditions.self, forKey: .additions)
    self.removals = try container.decodeIfPresent(ThreatEntryRemovals.self, forKey: .removals)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .newVersionToken) {
      self.newVersionToken = value
    }
    self.checksum = try container.decodeIfPresent(
      ComputeThreatListDiffResponse.Checksum.self, forKey: .checksum)
    self.recommendedNextDiff = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .recommendedNextDiff)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.responseType, forKey: .responseType)
    try container.encodeIfPresent(self.additions, forKey: .additions)
    try container.encodeIfPresent(self.removals, forKey: .removals)
    try container.encode(self.newVersionToken, forKey: .newVersionToken)
    try container.encodeIfPresent(self.checksum, forKey: .checksum)
    try container.encodeIfPresent(self.recommendedNextDiff, forKey: .recommendedNextDiff)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The expected state of a client's local database.
  public struct Checksum: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The SHA256 hash of the client state; that is, of the sorted list of all
    /// hashes present in the database.
    public var sha256: Foundation.Data = Foundation.Data()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Checksum`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Checksum().with { $0.sha256 = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sha256 = CodingKeys(stringValue: "sha256")

      static let _knownKeys: Set<Swift.String> = [
        "sha256"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .sha256) {
        self.sha256 = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sha256, forKey: .sha256)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.webrisk.v1.ComputeThreatListDiffResponse.Checksum"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of response sent to the client.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ResponseType: Codable, Equatable, Hashable, Sendable {
    /// Unknown.
    case unspecified
    /// Partial updates are applied to the client's existing local database.
    case diff
    /// Full updates resets the client's entire local database. This means
    /// that either the client had no state, was seriously out-of-date,
    /// or the client is believed to be corrupt.
    case reset
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .diff: return 1
      case .reset: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESPONSE_TYPE_UNSPECIFIED"
      case .diff: return "DIFF"
      case .reset: return "RESET"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResponseType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESPONSE_TYPE_UNSPECIFIED": self = .unspecified
      case "DIFF": self = .diff
      case "RESET": self = .reset
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResponseType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .diff
      case 2: self = .reset
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RESPONSE_TYPE_UNSPECIFIED")
      case .diff: return try container.encode("DIFF")
      case .reset: return try container.encode("RESET")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.webrisk.v1.ComputeThreatListDiffResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
