// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The Rice-Golomb encoded data. Used for sending compressed 4-byte hashes or
/// compressed removal indices.
public struct RiceDeltaEncoding: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The offset of the first entry in the encoded data, or, if only a single
  /// integer was encoded, that single integer's value. If the field is empty or
  /// missing, assume zero.
  public var firstValue: Swift.Int64 = Swift.Int64()

  /// The Golomb-Rice parameter, which is a number between 2 and 28. This field
  /// is missing (that is, zero) if `num_entries` is zero.
  public var riceParameter: Swift.Int32 = Swift.Int32()

  /// The number of entries that are delta encoded in the encoded data. If only a
  /// single integer was encoded, this will be zero and the single value will be
  /// stored in `first_value`.
  public var entryCount: Swift.Int32 = Swift.Int32()

  /// The encoded deltas that are encoded using the Golomb-Rice coder.
  public var encodedData: Foundation.Data = Foundation.Data()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RiceDeltaEncoding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RiceDeltaEncoding().with { $0.firstValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let firstValue = CodingKeys(stringValue: "firstValue")
    static let riceParameter = CodingKeys(stringValue: "riceParameter")
    static let entryCount = CodingKeys(stringValue: "entryCount")
    static let encodedData = CodingKeys(stringValue: "encodedData")

    static let _knownKeys: Set<Swift.String> = [
      "firstValue",
      "riceParameter",
      "entryCount",
      "encodedData",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .firstValue) {
      self.firstValue = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .riceParameter) {
      self.riceParameter = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .entryCount) {
      self.entryCount = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .encodedData) {
      self.encodedData = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.firstValue, forKey: .firstValue)
    try container.encode(self.riceParameter, forKey: .riceParameter)
    try container.encode(self.entryCount, forKey: .entryCount)
    try container.encode(self.encodedData, forKey: .encodedData)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.webrisk.v1.RiceDeltaEncoding"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
