// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct SearchHashesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The full hashes that matched the requested prefixes.
  /// The hash will be populated in the key.
  public var threats: [SearchHashesResponse.ThreatHash] = []

  /// For requested entities that did not match the threat list, how long to
  /// cache the response until.
  public var negativeExpireTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `SearchHashesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchHashesResponse().with { $0.threats = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Contains threat information on a matching hash.
  public struct ThreatHash: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The ThreatList this threat belongs to.
    /// This must contain at least one entry.
    public var threatTypes: [ThreatType] = []

    /// A 32 byte SHA256 hash. This field is in binary format. For JSON
    /// requests, hashes are base64-encoded.
    public var hash: Foundation.Data = Foundation.Data()

    /// The cache lifetime for the returned match. Clients must not cache this
    /// response past this timestamp to avoid false positives.
    public var expireTime: GoogleCloudWkt.Timestamp? = nil

    /// Initialize a new instance of `ThreatHash`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ThreatHash().with { $0.threatTypes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.webrisk.v1.SearchHashesResponse.ThreatHash"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.webrisk.v1.SearchHashesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
