// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

public struct SearchHashesResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The full hashes that matched the requested prefixes.
  /// The hash will be populated in the key.
  public var threats: [SearchHashesResponse.ThreatHash] = []

  /// For requested entities that did not match the threat list, how long to
  /// cache the response until.
  public var negativeExpireTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchHashesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchHashesResponse().with { $0.threats = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let threats = CodingKeys(stringValue: "threats")
    static let negativeExpireTime = CodingKeys(stringValue: "negativeExpireTime")

    static let _knownKeys: Set<Swift.String> = [
      "threats",
      "negativeExpireTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [SearchHashesResponse.ThreatHash].self, forKey: .threats)
    {
      self.threats = value
    }
    self.negativeExpireTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .negativeExpireTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.threats, forKey: .threats)
    try container.encodeIfPresent(self.negativeExpireTime, forKey: .negativeExpireTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Contains threat information on a matching hash.
  public struct ThreatHash: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The ThreatList this threat belongs to.
    /// This must contain at least one entry.
    public var threatTypes: [ThreatType] = []

    /// A 32 byte SHA256 hash. This field is in binary format. For JSON
    /// requests, hashes are base64-encoded.
    public var hash: Foundation.Data = Foundation.Data()

    /// The cache lifetime for the returned match. Clients must not cache this
    /// response past this timestamp to avoid false positives.
    public var expireTime: GoogleCloudWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ThreatHash`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ThreatHash().with { $0.threatTypes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let threatTypes = CodingKeys(stringValue: "threatTypes")
      static let hash = CodingKeys(stringValue: "hash")
      static let expireTime = CodingKeys(stringValue: "expireTime")

      static let _knownKeys: Set<Swift.String> = [
        "threatTypes",
        "hash",
        "expireTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([ThreatType].self, forKey: .threatTypes) {
        self.threatTypes = value
      }
      if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .hash) {
        self.hash = value
      }
      self.expireTime = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp.self, forKey: .expireTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.threatTypes, forKey: .threatTypes)
      try container.encode(self.hash, forKey: .hash)
      try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.webrisk.v1.SearchHashesResponse.ThreatHash"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.webrisk.v1.SearchHashesResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
