// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The type of threat. This maps directly to the threat list a threat may
/// belong to.
public enum ThreatType: Codable, Equatable, Sendable {
  /// No entries should match this threat type. This threat type is unused.
  case unspecified
  /// Malware targeting any platform.
  case malware
  /// Social engineering targeting any platform.
  case socialEngineering
  /// Unwanted software targeting any platform.
  case unwantedSoftware
  /// A list of extended coverage social engineering URIs targeting any
  /// platform.
  case socialEngineeringExtendedCoverage
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .malware: return 1
    case .socialEngineering: return 2
    case .unwantedSoftware: return 3
    case .socialEngineeringExtendedCoverage: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "THREAT_TYPE_UNSPECIFIED"
    case .malware: return "MALWARE"
    case .socialEngineering: return "SOCIAL_ENGINEERING"
    case .unwantedSoftware: return "UNWANTED_SOFTWARE"
    case .socialEngineeringExtendedCoverage: return "SOCIAL_ENGINEERING_EXTENDED_COVERAGE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ThreatType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "THREAT_TYPE_UNSPECIFIED": self = .unspecified
    case "MALWARE": self = .malware
    case "SOCIAL_ENGINEERING": self = .socialEngineering
    case "UNWANTED_SOFTWARE": self = .unwantedSoftware
    case "SOCIAL_ENGINEERING_EXTENDED_COVERAGE": self = .socialEngineeringExtendedCoverage
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ThreatType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .malware
    case 2: self = .socialEngineering
    case 3: self = .unwantedSoftware
    case 4: self = .socialEngineeringExtendedCoverage
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .malware: return try container.encode(1)
    case .socialEngineering: return try container.encode(2)
    case .unwantedSoftware: return try container.encode(3)
    case .socialEngineeringExtendedCoverage: return try container.encode(4)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
