// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Context about the submission including the type of abuse found on the URI and
/// supporting details.
public struct ThreatInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of abuse.
  public var abuseType: ThreatInfo.AbuseType = ThreatInfo.AbuseType()

  /// Confidence that the URI is unsafe.
  public var threatConfidence: ThreatInfo.Confidence? = nil

  /// Context about why the URI is unsafe.
  public var threatJustification: ThreatInfo.ThreatJustification? = nil

  /// Initialize a new instance of `ThreatInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ThreatInfo().with { $0.abuseType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Confidence that a URI is unsafe.
  public struct Confidence: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var value: OneOf_Value? = nil

    /// Initialize a new instance of `Confidence`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Confidence().with { $0.score = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case score = "score"
      case level = "level"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var value: OneOf_Value? = nil
      let valueCheckAndSet = {
        if value != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'value'"))
        }
        value = $0
      }
      if let score = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
        try valueCheckAndSet(.score(score))
      }
      if let level = try container.decodeIfPresent(
        ThreatInfo.Confidence.ConfidenceLevel.self, forKey: .level)
      {
        try valueCheckAndSet(.level(level))
      }
      self.value = value
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.value {
        switch choice {
        case .score(let value):
          try container.encode(value, forKey: .score)
        case .level(let value):
          try container.encode(value, forKey: .level)
        }
      }
    }

    /// Enum representation of confidence.
    public enum ConfidenceLevel: Codable, Equatable, Sendable {
      /// Default.
      case unspecified
      /// Less than 60% confidence that the URI is unsafe.
      case low
      /// Between 60% and 80% confidence that the URI is unsafe.
      case medium
      /// Greater than 80% confidence that the URI is unsafe.
      case high
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .low: return 1
        case .medium: return 2
        case .high: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CONFIDENCE_LEVEL_UNSPECIFIED"
        case .low: return "LOW"
        case .medium: return "MEDIUM"
        case .high: return "HIGH"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConfidenceLevel/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CONFIDENCE_LEVEL_UNSPECIFIED": self = .unspecified
        case "LOW": self = .low
        case "MEDIUM": self = .medium
        case "HIGH": self = .high
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConfidenceLevel/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .low
        case 2: self = .medium
        case 3: self = .high
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .low: return try container.encode(1)
        case .medium: return try container.encode(2)
        case .high: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public enum OneOf_Value: Codable, Equatable, Sendable {
      /// A decimal representation of confidence in the range of 0
      /// to 1 where 0 indicates no confidence and 1 indicates
      /// complete confidence.
      case score(Swift.Float)
      /// Enum representation of confidence.
      case level(ThreatInfo.Confidence.ConfidenceLevel)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.webrisk.v1.ThreatInfo.Confidence"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Context about why the URI is unsafe.
  public struct ThreatJustification: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Labels associated with this URI that explain how it was classified.
    public var labels: [ThreatInfo.ThreatJustification.JustificationLabel] = []

    /// Free-form context on why this URI is unsafe.
    public var comments: [Swift.String] = []

    /// Initialize a new instance of `ThreatJustification`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ThreatJustification().with { $0.labels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Labels that explain how the URI was classified.
    public enum JustificationLabel: Codable, Equatable, Sendable {
      /// Default.
      case unspecified
      /// The submitter manually verified that the submission is unsafe.
      case manualVerification
      /// The submitter received the submission from an end user.
      case userReport
      /// The submitter received the submission from an automated system.
      case automatedReport
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .manualVerification: return 1
        case .userReport: return 2
        case .automatedReport: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "JUSTIFICATION_LABEL_UNSPECIFIED"
        case .manualVerification: return "MANUAL_VERIFICATION"
        case .userReport: return "USER_REPORT"
        case .automatedReport: return "AUTOMATED_REPORT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:JustificationLabel/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "JUSTIFICATION_LABEL_UNSPECIFIED": self = .unspecified
        case "MANUAL_VERIFICATION": self = .manualVerification
        case "USER_REPORT": self = .userReport
        case "AUTOMATED_REPORT": self = .automatedReport
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:JustificationLabel/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .manualVerification
        case 2: self = .userReport
        case 3: self = .automatedReport
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .manualVerification: return try container.encode(1)
        case .userReport: return try container.encode(2)
        case .automatedReport: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.webrisk.v1.ThreatInfo.ThreatJustification"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The abuse type found on the URI.
  public enum AbuseType: Codable, Equatable, Sendable {
    /// Default.
    case unspecified
    /// The URI contains malware.
    case malware
    /// The URI contains social engineering.
    case socialEngineering
    /// The URI contains unwanted software.
    case unwantedSoftware
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .malware: return 1
      case .socialEngineering: return 2
      case .unwantedSoftware: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ABUSE_TYPE_UNSPECIFIED"
      case .malware: return "MALWARE"
      case .socialEngineering: return "SOCIAL_ENGINEERING"
      case .unwantedSoftware: return "UNWANTED_SOFTWARE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AbuseType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ABUSE_TYPE_UNSPECIFIED": self = .unspecified
      case "MALWARE": self = .malware
      case "SOCIAL_ENGINEERING": self = .socialEngineering
      case "UNWANTED_SOFTWARE": self = .unwantedSoftware
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AbuseType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .malware
      case 2: self = .socialEngineering
      case 3: self = .unwantedSoftware
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .malware: return try container.encode(1)
      case .socialEngineering: return try container.encode(2)
      case .unwantedSoftware: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.webrisk.v1.ThreatInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
