// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class WebRiskServiceLogging: WebRiskServiceStub {
    let inner: any WebRiskServiceStub
    let logger: Logger

    public init(_ inner: any WebRiskServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-webrisk-v1"
      logger[metadataKey: "gcp.client.service"] = "webrisk"
      logger[metadataKey: "gcp.experimental.swift.client"] = "WebRiskService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func computeThreatListDiff(
      request: ComputeThreatListDiffRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "computeThreatListDiff",
        action: {
          (r: ComputeThreatListDiffRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse
          in
          return try await self.inner.computeThreatListDiff(request: r, options: o)
        })
    }

    public func searchUris(
      request: SearchUrisRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.SearchUrisResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchUris",
        action: {
          (r: SearchUrisRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebRiskV1.SearchUrisResponse
          in
          return try await self.inner.searchUris(request: r, options: o)
        })
    }

    public func searchHashes(
      request: SearchHashesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.SearchHashesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchHashes",
        action: {
          (r: SearchHashesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebRiskV1.SearchHashesResponse
          in
          return try await self.inner.searchHashes(request: r, options: o)
        })
    }

    public func createSubmission(
      request: CreateSubmissionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.Submission {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSubmission",
        action: {
          (r: CreateSubmissionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebRiskV1.Submission
          in
          return try await self.inner.createSubmission(request: r, options: o)
        })
    }

    public func submitUri(
      request: SubmitUriRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "submitUri",
        action: {
          (r: SubmitUriRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.submitUri(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
