// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class WebRiskServiceRetry: WebRiskServiceStub {
    let inner: any WebRiskServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any WebRiskServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func computeThreatListDiff(
      request: ComputeThreatListDiffRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ComputeThreatListDiffRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse
          in
          return try await self.inner.computeThreatListDiff(request: r, options: o)
        })
    }

    public func searchUris(
      request: SearchUrisRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.SearchUrisResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchUrisRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebRiskV1.SearchUrisResponse
          in
          return try await self.inner.searchUris(request: r, options: o)
        })
    }

    public func searchHashes(
      request: SearchHashesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.SearchHashesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchHashesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebRiskV1.SearchHashesResponse
          in
          return try await self.inner.searchHashes(request: r, options: o)
        })
    }

    public func createSubmission(
      request: CreateSubmissionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.Submission {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSubmissionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebRiskV1.Submission
          in
          return try await self.inner.createSubmission(request: r, options: o)
        })
    }

    public func submitUri(
      request: SubmitUriRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SubmitUriRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.submitUri(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
