// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Web Risk API defines an interface to detect malicious URLs on your
/// website and in client applications.
///
/// @Snippet(path: "WebRiskServiceQuickstart")
public class WebRiskServiceClient: Clients.WebRiskServiceProtocol {
  let inner: any Clients.WebRiskServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `WebRiskServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.WebRiskServiceStub = try Clients.WebRiskServiceTransport(options)
    inner = Clients.WebRiskServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.WebRiskServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Gets the most recent threat list diffs. These diffs should be applied to
  /// a local database of hashes to keep it up-to-date. If the local database is
  /// empty or excessively out-of-date, a complete snapshot of the database will
  /// be returned. This Method only updates a single ThreatList at a time. To
  /// update multiple ThreatList databases, this method needs to be called once
  /// for each list.
  ///
  /// @Snippet(path: "WebRiskService_ComputeThreatListDiff")
  public func computeThreatListDiff(
    request: ComputeThreatListDiffRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse {
    try await self.inner.computeThreatListDiff(request: request, options: options)
  }

  /// This method is used to check whether a URI is on a given threatList.
  /// Multiple threatLists may be searched in a single query.
  /// The response will list all requested threatLists the URI was found to
  /// match. If the URI is not found on any of the requested ThreatList an
  /// empty response will be returned.
  ///
  /// @Snippet(path: "WebRiskService_SearchUris")
  public func searchUris(
    request: SearchUrisRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebRiskV1.SearchUrisResponse {
    try await self.inner.searchUris(request: request, options: options)
  }

  /// Gets the full hashes that match the requested hash prefix.
  /// This is used after a hash prefix is looked up in a threatList
  /// and there is a match. The client side threatList only holds partial hashes
  /// so the client must query this method to determine if there is a full
  /// hash match of a threat.
  ///
  /// @Snippet(path: "WebRiskService_SearchHashes")
  public func searchHashes(
    request: SearchHashesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebRiskV1.SearchHashesResponse {
    try await self.inner.searchHashes(request: request, options: options)
  }

  /// Creates a Submission of a URI suspected of containing phishing content to
  /// be reviewed. If the result verifies the existence of malicious phishing
  /// content, the site will be added to the [Google's Social Engineering
  /// lists](https://support.google.com/webmasters/answer/6350487/) in order to
  /// protect users that could get exposed to this threat in the future. Only
  /// allowlisted projects can use this method during Early Access. Please reach
  /// out to Sales or your customer engineer to obtain access.
  ///
  /// @Snippet(path: "WebRiskService_CreateSubmission")
  public func createSubmission(
    request: CreateSubmissionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebRiskV1.Submission {
    try await self.inner.createSubmission(request: request, options: options)
  }

  /// Submits a URI suspected of containing malicious content to be reviewed.
  /// Returns a google.longrunning.Operation which, once the review is complete,
  /// is updated with its result. You can use the [Pub/Sub API]
  /// (https://cloud.google.com/pubsub) to receive notifications for the returned
  /// Operation. If the result verifies the existence of malicious content, the
  /// site will be added to the [Google's Social Engineering lists]
  /// (https://support.google.com/webmasters/answer/6350487/) in order to
  /// protect users that could get exposed to this threat in the future. Only
  /// allowlisted projects can use this method during Early Access. Please reach
  /// out to Sales or your customer engineer to obtain access.
  ///
  /// @Snippet(path: "WebRiskService_SubmitUri")
  public func submitUri(
    request: SubmitUriRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.submitUri(request: request, options: options)
  }

  /// Submits a URI suspected of containing malicious content to be reviewed.
  /// Returns a google.longrunning.Operation which, once the review is complete,
  /// is updated with its result. You can use the [Pub/Sub API]
  /// (https://cloud.google.com/pubsub) to receive notifications for the returned
  /// Operation. If the result verifies the existence of malicious content, the
  /// site will be added to the [Google's Social Engineering lists]
  /// (https://support.google.com/webmasters/answer/6350487/) in order to
  /// protect users that could get exposed to this threat in the future. Only
  /// allowlisted projects can use this method during Early Access. Please reach
  /// out to Sales or your customer engineer to obtain access.
  ///
  /// @Snippet(path: "WebRiskService_SubmitUri")
  public func submitUri(
    withPolling: SubmitUriRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Submission> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Submission>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Submission(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.submitUri(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Submission>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "WebRiskService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "WebRiskService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "WebRiskService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "WebRiskService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "WebRiskService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `WebRiskServiceClient`.
  ///
  /// To mock `WebRiskServiceClient` change your functions to receive
  /// `some WebRiskServiceProtocol` or `any WebRiskServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol WebRiskServiceProtocol {
    /// See `WebRiskServiceClient.computeThreatListDiff`.
    func computeThreatListDiff(request: ComputeThreatListDiffRequest) async throws
      -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse

    /// See `WebRiskServiceClient.computeThreatListDiff`.
    func computeThreatListDiff(
      threatType: ThreatType,
      versionToken: Foundation.Data,
      constraints: ComputeThreatListDiffRequest.Constraints?,
    ) async throws -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse

    /// See `WebRiskServiceClient.searchUris`.
    func searchUris(request: SearchUrisRequest) async throws
      -> GoogleCloudWebRiskV1.SearchUrisResponse

    /// See `WebRiskServiceClient.searchUris`.
    func searchUris(
      uri: Swift.String,
      threatTypes: [ThreatType],
    ) async throws -> GoogleCloudWebRiskV1.SearchUrisResponse

    /// See `WebRiskServiceClient.searchHashes`.
    func searchHashes(request: SearchHashesRequest) async throws
      -> GoogleCloudWebRiskV1.SearchHashesResponse

    /// See `WebRiskServiceClient.searchHashes`.
    func searchHashes(
      hashPrefix: Foundation.Data,
      threatTypes: [ThreatType],
    ) async throws -> GoogleCloudWebRiskV1.SearchHashesResponse

    /// See `WebRiskServiceClient.createSubmission`.
    func createSubmission(request: CreateSubmissionRequest) async throws
      -> GoogleCloudWebRiskV1.Submission

    /// See `WebRiskServiceClient.createSubmission`.
    func createSubmission(
      parent: Swift.String,
      submission: Submission?,
    ) async throws -> GoogleCloudWebRiskV1.Submission

    /// See `WebRiskServiceClient.submitUri`.
    func submitUri(request: SubmitUriRequest) async throws -> GoogleLongRunning.Operation

    /// See `WebRiskServiceClient.submitUri`.
    func submitUri(withPolling: SubmitUriRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Submission>

    /// See `WebRiskServiceClient.submitUri`.
    func submitUri(
      parent: Swift.String,
      submission: Submission?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Submission>

    /// See `WebRiskServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `WebRiskServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WebRiskServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WebRiskServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `WebRiskServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `WebRiskServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `WebRiskServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `WebRiskServiceClient.computeThreatListDiff`.
    func computeThreatListDiff(
      request: ComputeThreatListDiffRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse

    /// See `WebRiskServiceClient.searchUris`.
    func searchUris(
      request: SearchUrisRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.SearchUrisResponse

    /// See `WebRiskServiceClient.searchHashes`.
    func searchHashes(
      request: SearchHashesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.SearchHashesResponse

    /// See `WebRiskServiceClient.createSubmission`.
    func createSubmission(
      request: CreateSubmissionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebRiskV1.Submission

    /// See `WebRiskServiceClient.submitUri`.
    func submitUri(
      request: SubmitUriRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `WebRiskServiceClient.submitUri`.
    func submitUri(
      withPolling: SubmitUriRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Submission>

    /// See `WebRiskServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `WebRiskServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `WebRiskServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `WebRiskServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.WebRiskServiceProtocol {
  public func computeThreatListDiff(request: ComputeThreatListDiffRequest) async throws
    -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse
  {
    try await self.computeThreatListDiff(request: request, options: .init())
  }

  public func computeThreatListDiff(
    request: ComputeThreatListDiffRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func computeThreatListDiff(
    threatType: ThreatType,
    versionToken: Foundation.Data,
    constraints: ComputeThreatListDiffRequest.Constraints?,
  ) async throws -> GoogleCloudWebRiskV1.ComputeThreatListDiffResponse {
    let request = ComputeThreatListDiffRequest().with {
      $0.threatType = threatType
      $0.versionToken = versionToken
      $0.constraints = constraints
    }
    return try await self.computeThreatListDiff(request: request)
  }

  public func searchUris(request: SearchUrisRequest) async throws
    -> GoogleCloudWebRiskV1.SearchUrisResponse
  {
    try await self.searchUris(request: request, options: .init())
  }

  public func searchUris(
    request: SearchUrisRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebRiskV1.SearchUrisResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchUris(
    uri: Swift.String,
    threatTypes: [ThreatType],
  ) async throws -> GoogleCloudWebRiskV1.SearchUrisResponse {
    let request = SearchUrisRequest().with {
      $0.uri = uri
      $0.threatTypes = threatTypes
    }
    return try await self.searchUris(request: request)
  }

  public func searchHashes(request: SearchHashesRequest) async throws
    -> GoogleCloudWebRiskV1.SearchHashesResponse
  {
    try await self.searchHashes(request: request, options: .init())
  }

  public func searchHashes(
    request: SearchHashesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebRiskV1.SearchHashesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchHashes(
    hashPrefix: Foundation.Data,
    threatTypes: [ThreatType],
  ) async throws -> GoogleCloudWebRiskV1.SearchHashesResponse {
    let request = SearchHashesRequest().with {
      $0.hashPrefix = hashPrefix
      $0.threatTypes = threatTypes
    }
    return try await self.searchHashes(request: request)
  }

  public func createSubmission(request: CreateSubmissionRequest) async throws
    -> GoogleCloudWebRiskV1.Submission
  {
    try await self.createSubmission(request: request, options: .init())
  }

  public func createSubmission(
    request: CreateSubmissionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebRiskV1.Submission {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSubmission(
    parent: Swift.String,
    submission: Submission?,
  ) async throws -> GoogleCloudWebRiskV1.Submission {
    let request = CreateSubmissionRequest().with {
      $0.parent = parent
      $0.submission = submission
    }
    return try await self.createSubmission(request: request)
  }

  public func submitUri(request: SubmitUriRequest) async throws -> GoogleLongRunning.Operation {
    try await self.submitUri(request: request, options: .init())
  }

  public func submitUri(
    request: SubmitUriRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func submitUri(withPolling: SubmitUriRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Submission>
  {
    try await self.submitUri(withPolling: withPolling, options: .init())
  }

  public func submitUri(
    withPolling: SubmitUriRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Submission> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Submission>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func submitUri(
    parent: Swift.String,
    submission: Submission?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Submission> {
    let request = SubmitUriRequest().with {
      $0.parent = parent
      $0.submission = submission
    }
    return try await self.submitUri(withPolling: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
